# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Obsidian"
license = "MIT"
licenselink = "https://github.com/alaindet/learn-go/blob/master/courses/hugo/portfolio/themes/obsidian/LICENSE"
description = "Obsidian Hugo Theme"
homepage = "https://github.com/alaindet/learn-go"
tags = ["black and white"]
features = []
min_version = "0.41.0"

[author]
  name = "Alain D'Ettorre"
  homepage = "https://github.com/alaindet"
