POST http://localhost:8080/events
content-type: application/json

{
  "name": "Test event",
  "description": "A test event",
  "location": "A test location",
  "dateTime": "2024-01-01T00:00:00.000Z"
}
