@port = 8080
@apiPrefix = api/v1
@baseUrl = http://localhost:{{port}}/{{apiPrefix}}
@eventId = 1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbmVAZXhhbXBsZS5jb20iLCJleHAiOjE3MjQ1NzczMTgsInVzZXJJZCI6Mn0.mhQkuTpQ_6G0W_nI4QnoMNMECv1wal-O_ZHwzqQA3wo

###

DELETE {{baseUrl}}/events/{{eventId}}
authorization: {{token}}
