@port = 8080
@apiPrefix = api/v1
@baseUrl = http://localhost:{{port}}/{{apiPrefix}}
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJleHAiOjE3MjQ1Nzk5NTksInVzZXJJZCI6MX0.mEbwSDddgv2fUkB2HYB5S6rKHKJOUgZ3xdavE9Eey2Y

###

POST {{baseUrl}}/events
content-type: application/json
authorization: {{token}}

{
  "name": "Test event",
  "description": "A test event",
  "location": "A test location",
  "dateTime": "2024-01-01T00:00:00.000Z"
}
