@port = 8080
@apiPrefix = api/v1
@baseUrl = http://localhost:{{port}}/{{apiPrefix}}
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbmVAZXhhbXBsZS5jb20iLCJleHAiOjE3MjQ1NzczMTgsInVzZXJJZCI6Mn0.mhQkuTpQ_6G0W_nI4QnoMNMECv1wal-O_ZHwzqQA3wo

###

POST {{baseUrl}}/events
content-type: application/json
authorization: {{token}}

{
  "name": "Test event",
  "description": "A test event",
  "location": "A test location",
  "dateTime": "2024-01-01T00:00:00.000Z"
}
