@port = 8080
@apiPrefix = api/v1
@baseUrl = http://localhost:{{port}}/{{apiPrefix}}

###

POST {{baseUrl}}/signin
content-type: application/json

{
  "email": "jane@example.com",
  "password": "jane@example.com"
}
