version: '3.8'

services:

  mariadb:
    image: mariadb:10.7
    working_dir: /application
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=progo
      - MYSQL_USER=progo
      - MYSQL_PASSWORD=progo
    ports:
      - '3306:3306'

  adminer:
    image: adminer:4.8.1
    ports:
      - '8081:8080'
    depends_on:
      - mariadb

volumes:
  db_data: {}
