version: '3.8'
services:

  db:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=greenlight
      - POSTGRES_PASSWORD=greenlight
      - POSTGRES_DB=greenlight
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./database/pg-init.sql:/docker-entrypoint-initdb.d/pg-init.sql

  adminer:
    image: adminer:4.8.1
    ports:
      - '8081:8080'

  # pgadmin:
  #   image: dpage/pgadmin4
  #   ports:
  #     - '5050:80'
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: greenlight@example.com
  #     PGADMIN_DEFAULT_PASSWORD: greenlight
  #   volumes:
  #     - pgadmindata:/var/lib/pgadmin

  # Or docker run -p 8025:8025 -p 1025:1025 mailhog/mailhog
  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  dbdata: {}
  # pgadmindata: {}
